name: "JenArgo"
mode: "dev"
port: 8000
version: "v1.0.0"
start_time: "2025-03-14"
machine_id: 1

log:
  level: "debug"
  filename: "log/JenArgo.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  db_type: mysql
  host: "10.0.0.101"
  port: 3306
  user: "JenArgo"
  password: ""
  dbname: "JenArgo"
  log_mode: false
  max_open_conns: 100  # 最大连接数
  max_idle_conns: 10  # 最大空闲连接
  max_life_time: 30 # 最大生存时间

ci_cd:
  copy_job_name: "inf-lappcenter"
  jenkins_url: "jenkins.evescn.com"
  user_password: "admin:......"
  prod_user_password: "admin:......"
  cocos_jenkins_url: ""
  cocos_user_password: ""

gitlab:
  gitlab_url: "https://gitlab.evescn.com"
  gitlab_token: ""

argocd:
  argocd_url: "https://test-argocd.evescn.com"
  argocd_name: "admin"
  argocd_password: ""
  argocd_repo : 'https://gitlab.evescn.com/ops/argocd-apps.git'
  argocd_log_follow: false
  argocd_log_tailLines: 200
